export const PANTALLAS = [
    { key: 'home', label: 'Home', acciones: ['ver'] },
    { key: 'atenciones', label: 'Atenciones', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar', 'agendar'] },
    { key: 'citas', label: 'Citas', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar', 'atender'] },
    { key: 'pacientes', label: 'Pacientes', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar', 'seguimiento'] },
    { key: 'consulta', label: 'Consultas', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar'] },
    { key: 'historias', label: 'Historias', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar'] },
    { key: 'enfermedades', label: 'Patologias', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'doctores', label: 'Doctores', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar'] },
    { key: 'usuarios', label: 'Usuarios', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar'] },
    { key: 'cargos', label: 'Cargos', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'profesion', label: 'Profesiones', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'roles', label: 'Seguridad y Roles', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'reposos', label: 'Reposos', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar'] },
    { key: 'bitacora', label: 'Seguimiento y Bitacora', acciones: ['ver'] },
    { key: 'departamentos', label: 'Departamentos', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'finalidades', label: 'Finalidades', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'categoria_e', label: 'Categoria de Patologias', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'categoria_m', label: 'Categoria de Medicamentos', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'medicamentos', label: 'Medicamentos', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar'] },
    { key: 'seguimiento', label: 'Seguimiento', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar'] },
];

export const ACCIONES = [
    { key: 'ver', label: 'Ver' },
    { key: 'crear', label: 'Crear' },
    { key: 'editar', label: 'Editar' },
    { key: 'eliminar', label: 'Eliminar' },
    { key: 'agendar', label: 'Agendar' },
    { key: 'atender', label: 'Atender' },
    { key: 'exportar', label: 'Exportar' },
    { key: 'seguimiento', label: 'Seguimiento' },
];